# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import gorpc_pb2 as gorpc__pb2


class GoRpcStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSample = channel.unary_unary(
        '/gorpc.GoRpc/GetSample',
        request_serializer=gorpc__pb2.SampleReq.SerializeToString,
        response_deserializer=gorpc__pb2.SampleRes.FromString,
        )


class GoRpcServicer(object):

  def GetSample(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GoRpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSample': grpc.unary_unary_rpc_method_handler(
          servicer.GetSample,
          request_deserializer=gorpc__pb2.SampleReq.FromString,
          response_serializer=gorpc__pb2.SampleRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gorpc.GoRpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
