// Code generated by protoc-gen-go.
// source: gorpc.proto
// DO NOT EDIT!

/*
Package gorpc is a generated protocol buffer package.

It is generated from these files:
	gorpc.proto

It has these top-level messages:
	SampleReq
	SampleRes
*/
package gorpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SampleReq struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *SampleReq) Reset()                    { *m = SampleReq{} }
func (m *SampleReq) String() string            { return proto.CompactTextString(m) }
func (*SampleReq) ProtoMessage()               {}
func (*SampleReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SampleReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SampleReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SampleRes struct {
	Mes string `protobuf:"bytes,1,opt,name=mes" json:"mes,omitempty"`
}

func (m *SampleRes) Reset()                    { *m = SampleRes{} }
func (m *SampleRes) String() string            { return proto.CompactTextString(m) }
func (*SampleRes) ProtoMessage()               {}
func (*SampleRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SampleRes) GetMes() string {
	if m != nil {
		return m.Mes
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleReq)(nil), "gorpc.SampleReq")
	proto.RegisterType((*SampleRes)(nil), "gorpc.SampleRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoRpc service

type GoRpcClient interface {
	GetSample(ctx context.Context, in *SampleReq, opts ...grpc.CallOption) (*SampleRes, error)
}

type goRpcClient struct {
	cc *grpc.ClientConn
}

func NewGoRpcClient(cc *grpc.ClientConn) GoRpcClient {
	return &goRpcClient{cc}
}

func (c *goRpcClient) GetSample(ctx context.Context, in *SampleReq, opts ...grpc.CallOption) (*SampleRes, error) {
	out := new(SampleRes)
	err := grpc.Invoke(ctx, "/gorpc.GoRpc/GetSample", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoRpc service

type GoRpcServer interface {
	GetSample(context.Context, *SampleReq) (*SampleRes, error)
}

func RegisterGoRpcServer(s *grpc.Server, srv GoRpcServer) {
	s.RegisterService(&_GoRpc_serviceDesc, srv)
}

func _GoRpc_GetSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoRpcServer).GetSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gorpc.GoRpc/GetSample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoRpcServer).GetSample(ctx, req.(*SampleReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gorpc.GoRpc",
	HandlerType: (*GoRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSample",
			Handler:    _GoRpc_GetSample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gorpc.proto",
}

func init() { proto.RegisterFile("gorpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcf, 0x2f, 0x2a,
	0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xf4, 0xb9, 0x38, 0x83,
	0x13, 0x73, 0x0b, 0x72, 0x52, 0x83, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x59, 0x84, 0x86, 0x62, 0x21, 0x01,
	0x2e, 0xe6, 0xdc, 0xd4, 0x62, 0xb0, 0x0e, 0xce, 0x20, 0x10, 0xd3, 0xc8, 0x8a, 0x8b, 0xd5, 0x3d,
	0x3f, 0xa8, 0x20, 0x59, 0xc8, 0x90, 0x8b, 0xd3, 0x3d, 0xb5, 0x04, 0xa2, 0x54, 0x48, 0x40, 0x0f,
	0x62, 0x35, 0xdc, 0x2a, 0x29, 0x74, 0x91, 0x62, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xcb, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xfc, 0x55, 0x71, 0xa8, 0x00, 0x00, 0x00,
}
