# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gorpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gorpc.proto',
  package='gorpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0bgorpc.proto\x12\x05gorpc\"%\n\tSampleReq\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x18\n\tSampleRes\x12\x0b\n\x03mes\x18\x01 \x01(\t2:\n\x05GoRpc\x12\x31\n\tGetSample\x12\x10.gorpc.SampleReq\x1a\x10.gorpc.SampleRes\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SAMPLEREQ = _descriptor.Descriptor(
  name='SampleReq',
  full_name='gorpc.SampleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gorpc.SampleReq.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='gorpc.SampleReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=59,
)


_SAMPLERES = _descriptor.Descriptor(
  name='SampleRes',
  full_name='gorpc.SampleRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mes', full_name='gorpc.SampleRes.mes', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['SampleReq'] = _SAMPLEREQ
DESCRIPTOR.message_types_by_name['SampleRes'] = _SAMPLERES

SampleReq = _reflection.GeneratedProtocolMessageType('SampleReq', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEREQ,
  __module__ = 'gorpc_pb2'
  # @@protoc_insertion_point(class_scope:gorpc.SampleReq)
  ))
_sym_db.RegisterMessage(SampleReq)

SampleRes = _reflection.GeneratedProtocolMessageType('SampleRes', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLERES,
  __module__ = 'gorpc_pb2'
  # @@protoc_insertion_point(class_scope:gorpc.SampleRes)
  ))
_sym_db.RegisterMessage(SampleRes)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class GoRpcStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetSample = channel.unary_unary(
          '/gorpc.GoRpc/GetSample',
          request_serializer=SampleReq.SerializeToString,
          response_deserializer=SampleRes.FromString,
          )


  class GoRpcServicer(object):

    def GetSample(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_GoRpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetSample': grpc.unary_unary_rpc_method_handler(
            servicer.GetSample,
            request_deserializer=SampleReq.FromString,
            response_serializer=SampleRes.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'gorpc.GoRpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaGoRpcServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetSample(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaGoRpcStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetSample(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetSample.future = None


  def beta_create_GoRpc_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('gorpc.GoRpc', 'GetSample'): SampleReq.FromString,
    }
    response_serializers = {
      ('gorpc.GoRpc', 'GetSample'): SampleRes.SerializeToString,
    }
    method_implementations = {
      ('gorpc.GoRpc', 'GetSample'): face_utilities.unary_unary_inline(servicer.GetSample),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_GoRpc_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('gorpc.GoRpc', 'GetSample'): SampleReq.SerializeToString,
    }
    response_deserializers = {
      ('gorpc.GoRpc', 'GetSample'): SampleRes.FromString,
    }
    cardinalities = {
      'GetSample': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'gorpc.GoRpc', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
